{
    TChain chain("tmatch");
    chain.Add("test1.root");
    chain.Add("test2.root");
    chain.Add("test3.root");
    chain.Add("test4.root");
    chain.Add("test5.root");
    chain.Add("test6.root");
    chain.Add("test7.root");
    chain.Add("test8.root");
    chain.Add("test9.root");
    chain.Add("test10.root");
    chain.Add("test11.root");
    chain.Add("test12.root");
    chain.Add("test13.root");
    chain.Add("test14.root");
    chain.Add("test15.root");
    chain.Add("test16.root");
    chain.Add("test17.root");
    chain.Add("test18.root");
    chain.Add("test19.root");
    chain.Add("test20.root");
    chain.Add("test21.root");
    chain.Add("test22.root");
    chain.Add("test23.root");
    chain.Add("test24.root");
    chain.Add("test25.root");
    chain.Add("test26.root");
    chain.Add("test27.root");
    chain.Add("test28.root");
    chain.Add("test29.root");
    chain.Add("test30.root");
    chain.Add("test31.root");
    chain.Add("test32.root");
    chain.Add("test33.root");
    chain.Add("test34.root");
    chain.Add("test35.root");
    chain.Add("test36.root");
    chain.Add("test37.root");
    chain.Add("test38.root");
    chain.Add("test39.root");
    chain.Add("test40.root");
    chain.Add("test41.root");
    chain.Add("test42.root");
    chain.Add("test43.root");
    chain.Add("test44.root");
    chain.Add("test45.root");
    chain.Add("test46.root");
    TFile f("comb.root","recreate");
    TTree t("tmatch","A combined tree with matching data");
    t->Branch("total_number", &cb_tot, "b_tot/L");
    t->Branch("entry_number", &cb_entry, "b_entry/L");
    t->Branch("igcell", &cb_igcell, "b_igcell/I");
    t->Branch("fee_b", &cb_fee_b, "b_fee_b/I");
    t->Branch("channel", &b_ch, "b_ch/I");
    t->Branch("X", &cb_x, "b_x/F");
    t->Branch("Y", &cb_y, "b_y/F");
    t->Branch("anode_b", &cb_anode_b, "b_anode_big/I");
    t->Branch("dynode_b", &cb_dynode_b, "b_dynode_big/I");
    t->Branch("npe_b", &cb_npe_b, "b_npe_b/D");
    t->Branch("time_b", &cb_time_b, "b_time_big/L");
    t->Branch("fee_s", &cb_fee_s, "b_fee_s/I");
    t->Branch("db", &cb_db, "b_db/I");
    t->Branch("pmt", &cb_pmt, "b_pmt/I");
    t->Branch("anode_s", &cb_anode_s, "b_anode_peak/I");
    t->Branch("dynode_s", &cb_dynode_s, "b_dynode_peak/I");
    t->Branch("npe_s", &cb_npe_s, "b_npe_s/D");
    t->Branch("time_s", &cb_time_s, "b_time_small/L");
    t->Branch("time_df", &cb_time_diff, "b_time_s - b_time_b /L");
}